### PR TITLE
ADDING Vigenere Cipher

### PR DESCRIPTION
**Pull request by rkraja2751**
I am creating a pull request for...

- [ ] New algorithm

### CODE REVIEW

**Review by hemanth-kotagiri — COMMENTED** [review]
Hello, @rkraja2751. Thanks for your interest in contributing to this repository. I am sorry to tell you that the code that you've written is strikingly similar to the code in this website:
https://www.geeksforgeeks.org/vigenere-cipher/
which is authored by someone else. We do not encourage plagiarism.

Here are a few things that you need to consider before contributing to any repository:

1. Always read the contribution guidelines of the specific repository that you are contributing to.
2. You can always refer to any online resources for the feature/fix that you are working on to contribute, but never copy-paste code which will result in categorizing your PR under Plagiarism.
3. Always write clean and well-structured code. It's a best practice that you can do while contributing to Open Source.


Looking forward to your next PR!
Thanks!

**Comment by hemanth-kotagiri** [comment]
@abranhe, please check out my review and if you agree with me, add the ``Plagiarism`` label and close this PR.

Thanks!

**Comment by rkraja2751** [comment]
> Hello, @rkraja2751. Thanks for your interest in contributing to this repository. I am sorry to tell you that the code that you've written is strikingly similar to the code in this website:
> https://www.geeksforgeeks.org/vigenere-cipher/
> which is authored by someone else. We do not encourage plagiarism.
> 
> Here are a few things that you need to consider before contributing to any repository:
> 
>     1. Always read the contribution guidelines of the specific repository that you are contributing to.
> 
>     2. You can always refer to any online resources for the feature/fix that you are working on to contribute, but never copy-paste code which will result in categorizing your PR under Plagiarism.
> 
>     3. Always write clean and well-structured code. It's a best practice that you can do while contributing to Open Source.
> 
> 
> Looking forward to your next PR!
> Thanks!

@hemanth-kotagiri  
Really Sorry, for that. I will take care of it from next time.

**Comment by hemanth-kotagiri** [comment]
Hey @rkraja2751! Don't be sorry! It's just a mistake that you've done and you're supposed to learn from it! Next time, please consider the points I mentioned before raising PRs in any repository, it will help you!

Thanks, again!

**Pull request closed without merging**
